# Generated by Django 2.1.1 on 2018-11-08 18:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_auto_20180413_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='min_odr_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Minimal Order Amount'),
        ),
    ]
