# Generated by Django 2.1.1 on 2018-11-08 19:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_voucher_minimal_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='minimal_order_amount',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_odr_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Minimal Order Amount'),
        ),
    ]
