# Generated by Django 2.1.1 on 2018-11-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_voucherdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherData',
        ),
    ]
