# Generated by Django 2.1.1 on 2018-11-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0016_voucherdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherDetail',
        ),
    ]
