# Generated by Django 2.1.1 on 2018-11-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0017_delete_voucherdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='min_odr_amount',
            new_name='minimal_order_amount',
        ),
    ]
