# Generated by Django 2.1.1 on 2018-11-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0018_auto_20181109_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='minimal_order_amount',
            new_name='min_odr_amount',
        ),
    ]
