# Generated by Django 2.1.1 on 2018-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0019_auto_20181111_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='min_odr_weight',
            field=models.IntegerField(default=0, verbose_name='Minimal Order Weight'),
        ),
    ]
