# Generated by Django 2.1.1 on 2018-12-17 07:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0021_remove_voucher_min_odr_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='min_odr_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Minimal Order Weight'),
        ),
    ]
