# Generated by Django 2.1.1 on 2018-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0022_voucher_min_odr_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='ship_method',
            field=models.CharField(default='', max_length=30, verbose_name='Courier Method'),
        ),
    ]
