# Generated by Django 2.1.1 on 2018-12-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0023_voucher_ship_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='ship_method',
            field=models.CharField(default=0, max_length=30, verbose_name='Courier Method'),
        ),
    ]
