# Generated by Django 2.1.1 on 2018-12-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0024_auto_20181217_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='min_odr_weight',
        ),
    ]
