# Generated by Django 2.1.1 on 2018-12-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0025_remove_voucher_min_odr_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='ship_method',
            new_name='shipping_method',
        ),
    ]
