# Generated by Django 2.1.1 on 2018-10-03 10:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_regenerate_user_address_hashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='address.Country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='address.District')),
            ],
            options={
                'db_table': 'subdistrict',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('postcode', models.CharField(default='', max_length=10, verbose_name='Postcode')),
                ('name', models.CharField(max_length=100)),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='address.Subdistrict')),
            ],
            options={
                'db_table': 'village',
            },
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(default='ID', on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='Alamat'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='address.State'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.State', verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='regency_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.District', verbose_name='Kota/Kabupaten'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='subdistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Subdistrict', verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Village', verbose_name='Desa/Kelurahan'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('subdistrict', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='subdistrict',
            unique_together={('district', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
    ]
