# Generated by Django 2.0 on 2019-01-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_useraddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='phone',
        ),
    ]
