# Generated by Django 2.0 on 2018-12-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Highlight Product'),
        ),
    ]
