# Generated by Django 2.1.1 on 2018-12-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_rangedestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedestination',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('', ''), ('state', 'State'), ('district', 'District'), ('subdistrict', 'Subdistrict'), ('village', 'Village')], max_length=12),
        ),
    ]
