# Generated by Django 2.1.1 on 2018-12-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_auto_20181212_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='range_destination',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
