# Generated by Django 2.1.1 on 2018-12-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20181212_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='offer.Range', verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='offer.Range', verbose_name='Range'),
        ),
    ]
