# Generated by Django 2.1.1 on 2018-12-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_auto_20181219_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedestination',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('', ''), ('allstate', 'All State'), ('state', 'State'), ('district', 'District'), ('subdistrict', 'Subdistrict'), ('village', 'Village')], max_length=12),
        ),
    ]
