# Generated by Django 2.1.1 on 2018-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_auto_20181219_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangedestination',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('', ''), ('allarea', 'All'), ('state', 'State'), ('district', 'District'), ('subdistrict', 'Subdistrict'), ('village', 'Village')], max_length=12),
        ),
    ]
