# Generated by Django 2.0 on 2019-01-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20160323_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='source_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
