# Generated by Django 2.0 on 2019-01-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190117_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetype',
            name='code',
            field=models.CharField(max_length=32),
        ),
    ]
