# Generated by Django 2.0 on 2019-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20190124_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='amount_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Amount Fee'),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='bank_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Bank Fee'),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='percent_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Percent Fee'),
        ),
    ]
