# Generated by Django 2.1.1 on 2018-10-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181003_1752'),
        ('order', '0005_update_email_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.State', verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='regency_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.District', verbose_name='Kota/Kabupaten'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='subdistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Subdistrict', verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Village', verbose_name='Desa/Kelurahan'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(default='ID', on_delete=django.db.models.deletion.CASCADE, to='address.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='line1',
            field=models.CharField(max_length=255, verbose_name='Alamat'),
        ),
    ]
