# Generated by Django 2.1.1 on 2018-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181004_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='line_price_after_discounts_excl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price after discounts (excl. tax)'),
        ),
        migrations.AddField(
            model_name='line',
            name='line_price_after_discounts_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price after discounts (inc. tax)'),
        ),
    ]
