# Generated by Django 2.0 on 2019-01-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181121_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernote',
            name='new_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='old_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
