# Generated by Django 2.0 on 2018-12-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image_desktop', models.ImageField(upload_to='campaign/banner/', verbose_name='Image Desktop')),
                ('image_mobile', models.ImageField(upload_to='campaign/banner/', verbose_name='Image Mobile')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('url', models.URLField(default='', verbose_name='Url')),
                ('number', models.IntegerField(default=1, verbose_name='Number')),
                ('valid_from', models.DateTimeField(default='', verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(default='', verbose_name='Valid Until')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BannerMini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='campaign/banner_mini/', verbose_name='Image')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('caption', models.TextField(verbose_name='Caption')),
                ('url', models.CharField(max_length=255, verbose_name='Click URL')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('sort_priority', models.IntegerField(verbose_name='Sort Priority')),
                ('valid_from', models.DateTimeField(default='', verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(default='', verbose_name='Valid Until')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'BannerMini',
                'verbose_name_plural': 'BannerMinis',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='campaign/endorsement/', verbose_name='Image')),
                ('name', models.CharField(max_length=200, verbose_name='Endorsement Name')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('caption', models.TextField(verbose_name='Caption')),
                ('url', models.CharField(max_length=255, verbose_name='Click URL')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('sort_priority', models.IntegerField(verbose_name='Sort Priority')),
                ('valid_from', models.DateTimeField(default='', verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(default='', verbose_name='Valid Until')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Endorsement',
                'verbose_name_plural': 'Endorsements',
                'ordering': ['-date_created'],
            },
        ),
    ]
