# Generated by Django 2.0 on 2018-12-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermini',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='bannermini',
            name='valid_until',
        ),
    ]
