# Generated by Django 2.0 on 2019-02-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20181210_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermini',
            name='sort_priority',
            field=models.IntegerField(default=0, verbose_name='Sort Priority'),
        ),
    ]
